import { writeFileSync } from "fs";

const DebugSvg = false;

type Vector = {
  x: number,
  y: number,
  z: number
};

type Ray = {
  name: string,
  direction: Vector,
  source: Vector,
  target: Vector,
  force: number,
  color: Vector
};


function length(v: Vector): number {
  return Math.sqrt(v.x * v.x + v.y * v.y + v.z * v.z) as number;
}

function add(a: Vector, b: Vector): Vector {
  return { x: a.x + b.x, y: a.y + b.y, z: a.z + b.z }
}

function subtract(a: Vector, b: Vector): Vector {
  return { x: a.x - b.x, y: a.y - b.y, z: a.z - b.z };
}

function mult(a: Vector, b: number): Vector {
  return { x: a.x * b, y: a.y * b, z: a.z * b }
}

function raymarch(source: Vector, direction: Vector, target: Vector, forceConstant = 1.0): Vector[] {
  const MaxSteps = 3000;
  let result: Vector[] = [];
  let position = source;
  let dir = direction;
  for (let i = 0; i < MaxSteps; i++) {
    // Raymarch position
    let p = add(position, dir);

    // Update direction vector
    let r2 = length(p) * length(p);
    let force = -1.0 * forceConstant / r2;
    // Normalizing the vector as well
    let gravity = mult(p, force / length(p));
    let newDir = add(dir, gravity);

    result.push(p);

    position = p;
    dir = newDir;

    if (position.x < -source.x) {
      break;
    }
  }

  return result;
}

function distance(points: Vector[], target: Vector): number {
  let diff = subtract(points[points.length - 1], target);
  let distance = length(diff);
  return distance;
}

function writeDataAsset(rays: Ray[], baseName: string) {
  for (let r of rays) {
    let ray = raymarch(r.source, r.direction, r.target, r.force);

    let res = `-- This asset is autogenerated through the gravitationallensing.ts\n\n`;
    res = `${res}local transform = asset.require(\"./holder.asset\")\n\n`;
    res = `${res}local Translation = {\n  Type = "TimelineTranslation",\n  Keyframes = {\n`;

    // The number was eyeballed to make the values start at 2000 JAN 01 12:00:00 UTC
    let count = 65;
    for (let v of ray) {
      res = `${res}    [openspace.time.convertTime(${count})] = {\n      Type = "StaticTranslation",\n      Position = { ${v.x}, ${v.y}, ${v.z} }\n    },\n`;
      count = count + 1;
    }
    res = `${res}\n  }\n}\n\n`;

    res = `${res}local Trail = {\n  Identifier = "GravLensingTrail_${baseName}_${r.name}",\n  Parent = transform.GravLensingHolder.Identifier,\n  Renderable = {\n    Type = "RenderableTrailTrajectory",\n    Translation = Translation,\n    Color = { ${r.color.x}, ${r.color.y}, ${r.color.z} },\n    LineWidth = 15,\n    StartTime = "2000 JAN 01 12:00:00",\n    EndTime = "2000 JAN 02 12:00:00",\n    SampleInterval = 1,\n    EnableFade = false\n  },\n  GUI = {\n    Name = "GravLensingTrail ${r.name}",\n    Path = "/SpaceNight/2025-09/Gravitational Lensing/Trails/${baseName}",\n    Focusable = false\n  }\n}\n\n`

    res = `${res}asset.onInitialize(function()\n`;
    res = `${res}  openspace.addSceneGraphNode(Trail)\n`;
    res = `${res}end)\n\n`

    res = `${res}asset.onDeinitialize(function()\n`;
    res = `${res}  openspace.removeSceneGraphNode(Trail)\n`;
    res = `${res}end)\n\n`
    writeFileSync(`assets/${baseName}_${r.name}.asset`, res);


    if (DebugSvg) {
      let res = `<html><svg width="1000" height="1000" xmlns="http://www.w3.org/2000/svg">\n`;

      res = `${res}<g transform="translate(500 500)">\n`;

      res = `${res}<ellipse cx="${Source.x * 10}" cy="${Source.y * 10}" rx="4" ry="4" fill="red"></ellipse>\n`;
      res = `${res}<ellipse cx="${-Source.x * 10}" cy="${-Source.y * 10}" rx="4" ry="4" fill="blue"></ellipse>\n`;
      res = `${res}<ellipse cx="0.0" cy="0.0" rx="4" ry="4" fill="res"></ellipse>\n`;

      for (let v of ray) {
        let line = `<ellipse cx="${v.x * 10}" cy="${v.y * 10}" rx="1" ry="1" fill="black"></ellipse>\n`;
        res = `${res}${line}`;
      }

      res = `${res}</g>\n`;
      res = `${res}</svg></html>`;

      writeFileSync(`assets/${baseName}_${r.name}_xy.html`, res);


      res = `<html><svg width="1000" height="1000" xmlns="http://www.w3.org/2000/svg">\n`;

      res = `${res}<g transform="translate(500 500)">\n`;

      res = `${res}<ellipse cx="${Source.y * 10}" cy="${Source.z * 10}" rx="4" ry="4" fill="red"></ellipse>\n`;
      res = `${res}<ellipse cx="${-Source.y * 10}" cy="${-Source.z * 10}" rx="4" ry="4" fill="blue"></ellipse>\n`;
      res = `${res}<ellipse cx="0.0" cy="0.0" rx="4" ry="4" fill="res"></ellipse>\n`;

      for (let v of ray) {
        let line = `<ellipse cx="${v.y * 10}" cy="${v.z * 10}" rx="1" ry="1" fill="black"></ellipse>\n`;
        res = `${res}${line}`;
      }

      res = `${res}</g>\n`;
      res = `${res}</svg></html>`;

      writeFileSync(`assets/${baseName}_${r.name}_yz.html`, res);


      res = `<html><svg width="1000" height="1000" xmlns="http://www.w3.org/2000/svg">\n`;

      res = `${res}<g transform="translate(500 500)">\n`;

      res = `${res}<ellipse cx="${Source.x * 10}" cy="${Source.z * 10}" rx="4" ry="4" fill="red"></ellipse>\n`;
      res = `${res}<ellipse cx="${-Source.x * 10}" cy="${-Source.z * 10}" rx="4" ry="4" fill="blue"></ellipse>\n`;
      res = `${res}<ellipse cx="0.0" cy="0.0" rx="4" ry="4" fill="res"></ellipse>\n`;

      for (let v of ray) {
        let line = `<ellipse cx="${v.x * 10}" cy="${v.z * 10}" rx="1" ry="1" fill="black"></ellipse>\n`;
        res = `${res}${line}`;
      }

      res = `${res}</g>\n`;
      res = `${res}</svg></html>`;

      writeFileSync(`assets/${baseName}_${r.name}_xz.html`, res);
    }
  }
}

function writeMainAsset(rays: Ray[], baseName: string) {
  let asset = "-- This asset is autogenerated through the gravitationallensing.ts\n\n";

  for (let r of rays) {
    asset = `${asset}asset.require("./${baseName}_${r.name}")\n`
  }
  writeFileSync(`assets/${baseName}_trails.asset`, asset);
}

//
// Setup
//
const Source: Vector = { x: 20.0, y: 0.0, z: 0.0 };


//
// Main
//
const ForceConstant = 0.008;
let symmetricRays = [
  {
    name: "00",
    direction: { x: -0.025, y: -0.020, z: 0.0 },
    source: Source,
    target: { x: -Source.x, y: Source.x, z: Source.z },
    // source: add(Source, { x: 0.0, y: -1, z: -1 }),
    force: ForceConstant,
    color: { x: 0.85, y: 0.65, z: 0.05 }
  },
  {
    name: "01",
    direction: { x: -0.025, y:  0.020, z: 0.0 },
    source: Source,
    target: { x: -Source.x, y: Source.x, z: Source.z },
    force: ForceConstant,
    color: { x: 0.85, y: 0.65, z: 0.05 }
  },
  {
    name: "10",
    direction: { x: -0.025, y:  0.0, z: -0.020 },
    source: Source,
    target: { x: -Source.x, y: Source.x, z: Source.z },
    force: ForceConstant,
    color: { x: 0.85, y: 0.65, z: 0.05 }
  },
  {
    name: "11",
    direction: { x: -0.025, y:  0.0, z: 0.020 },
    source: Source,
    target: { x: -Source.x, y: Source.x, z: Source.z },
    force: ForceConstant,
    color: { x: 0.85, y: 0.65, z: 0.05 }
  }
];

writeDataAsset(symmetricRays, "symmetric");
writeMainAsset(symmetricRays, "symmetric");



let asymmetricRays = [
  {
    name: "00",
    direction: { x: -0.015, y: -0.018, z: -0.0115 },
    source: add(Source, { x: 0.0, y: -5, z: -5 }),
    target: { x: -Source.x, y: Source.x, z: Source.z },
    force: ForceConstant * 1.65,
    color: { x: 0.85, y: 0.65, z: 0.05 }
  },
  {
    name: "01",
    direction: { x: -0.015, y:  0.009, z: 0.0075 },
    source: add(Source, { x: 0.0, y: -5, z: -5 }),
    target: { x: -Source.x, y: Source.x, z: Source.z },
    force: ForceConstant / 6,
    color: { x: 0.85, y: 0.65, z: 0.05 }
  },
  {
    name: "10",
    direction: { x: -0.02, y: -0.01, z: -0.019 },
    source: add(Source, { x: 0.0, y: -5, z: -5 }),
    target: { x: -Source.x, y: Source.x, z: Source.z },
    force: ForceConstant * 1.85,
    color: { x: 0.85, y: 0.65, z: 0.05 }
  },
  {
    name: "11",
    direction: { x: -0.01, y: -0.0165, z: 0.01285 },
    source: add(Source, { x: 0.0, y: -5, z: -5 }),
    target: { x: -Source.x, y: Source.x, z: Source.z },
    force: ForceConstant * 1.255,
    color: { x: 0.85, y: 0.65, z: 0.05 }
  }
];
writeDataAsset(asymmetricRays, "asymmetric");
writeMainAsset(asymmetricRays, "asymmetric");


if (false) {
  let testRays = [];
  let count = 0;

  let yMin = -0.05;
  let yMax = 0.05;
  let total = (yMax - yMin) / 0.0001;

  let closest = Number.MAX_VALUE;
  for (let y = yMin; y <= yMax; y += 0.001) {
    for (let z = -0.035; z <= 0.035; z += 0.001) {
      for (let fc = 0.5; fc <= 1.5; fc += 0.01) {
        let ray = {
          name: "",
          direction: { x: -0.01, y: y, z: z },
          source: add(Source, { x: 0.0, y: -5, z: -5 }),
          target: { x: -Source.x, y: Source.y, z: Source.z },
          force: ForceConstant * fc,
          color: { x: 0.85, y: 0.65, z: 0.05 }
        }

        let r = raymarch(ray.source, ray.direction, ray.target, ray.force);

        let d = distance(r, ray.target);
        const Radius = 0.05;
        if (d < Radius) {
          ray.name = `${d.toString().replaceAll(".", "_")}_${y.toString().replaceAll(".", "_")}${z.toString().replaceAll(".", "_")}`;
          testRays.push(ray);
        }

        if (d < closest) {
          closest = d;
        }
      }
    }
    console.log(`${count / total}`)
    count++;
  }
  console.log(`Closest: ${closest}`)
  writeDataAsset(testRays, "testRays");
  writeMainAsset(testRays, "testRays");
}
