# Saturn Moon Lookup Table (Complete - including provisional designations)
# Data: group, orbital_period_days, diameter_km
# Note: Negative orbital periods indicate retrograde orbits.
# Diameter values are approximate for most irregular/provisional moons.

saturn_moons = {
    # --- Inner / Regular Moons ---
    "S/2009 S 1":   {"group": "inner ring",                    "orbital_period_days": 0.47150,    "diameter_km": 0.3},
    "Pan":          {"group": "inner ring",                    "orbital_period_days": 0.57505,    "diameter_km": 28.2},
    "Daphnis":      {"group": "inner ring",                    "orbital_period_days": 0.59408,    "diameter_km": 7.6},
    "Atlas":        {"group": "inner ring",                    "orbital_period_days": 0.60460,    "diameter_km": 30.2},
    "Prometheus":   {"group": "inner ring",                    "orbital_period_days": 0.61588,    "diameter_km": 86.2},
    "Pandora":      {"group": "inner ring",                    "orbital_period_days": 0.63137,    "diameter_km": 81.4},
    "Epimetheus":   {"group": "co-orbital (with Janus)",       "orbital_period_days": 0.69701,    "diameter_km": 116.2},
    "Janus":        {"group": "co-orbital (with Epimetheus)",  "orbital_period_days": 0.69735,    "diameter_km": 179.0},
    "Aegaeon":      {"group": "ring-embedded",                 "orbital_period_days": 0.80812,    "diameter_km": 0.66},
    "Mimas":        {"group": "regular (round)",               "orbital_period_days": 0.94242,    "diameter_km": 396.4},
    "Methone":      {"group": "ring-embedded",                 "orbital_period_days": 1.00955,    "diameter_km": 2.9},
    "Anthe":        {"group": "ring-embedded",                 "orbital_period_days": 1.03890,    "diameter_km": 1.8},
    "Pallene":      {"group": "ring-embedded",                 "orbital_period_days": 1.15606,    "diameter_km": 4.44},
    "Enceladus":    {"group": "regular (round)",               "orbital_period_days": 1.37022,    "diameter_km": 504.2},
    "Tethys":       {"group": "regular (round)",               "orbital_period_days": 1.88780,    "diameter_km": 1062.2},
    "Telesto":      {"group": "trojan (Tethys L4)",            "orbital_period_days": 1.88780,    "diameter_km": 24.8},
    "Calypso":      {"group": "trojan (Tethys L5)",            "orbital_period_days": 1.88780,    "diameter_km": 21.4},
    "Helene":       {"group": "trojan (Dione L4)",             "orbital_period_days": 2.73692,    "diameter_km": 35.2},
    "Polydeuces":   {"group": "trojan (Dione L5)",             "orbital_period_days": 2.73692,    "diameter_km": 2.6},
    "Dione":        {"group": "regular (round)",               "orbital_period_days": 2.73692,    "diameter_km": 1122.8},
    "Rhea":         {"group": "regular (round)",               "orbital_period_days": 4.51750,    "diameter_km": 1527.6},
    "Titan":        {"group": "regular (round)",               "orbital_period_days": 15.9454,    "diameter_km": 5149.46},
    "Hyperion":     {"group": "regular",                       "orbital_period_days": 21.2767,    "diameter_km": 270.0},
    "Iapetus":      {"group": "regular (round)",               "orbital_period_days": 79.3310,    "diameter_km": 1468.6},

    # --- Inuit Group ---
    "S/2023 S 1":   {"group": "Inuit (Kiviuq)",               "orbital_period_days": 442.86,     "diameter_km": 3.0},
    "S/2019 S 1":   {"group": "Inuit (Kiviuq)",               "orbital_period_days": 445.17,     "diameter_km": 5.0},
    "S/2004 S 54":  {"group": "Inuit (Kiviuq)",               "orbital_period_days": 447.14,     "diameter_km": 4.0},
    "S/2004 S 55":  {"group": "Inuit (Kiviuq)",               "orbital_period_days": 448.16,     "diameter_km": 3.0},
    "S/2020 S 11":  {"group": "Inuit (Kiviuq)",               "orbital_period_days": 448.21,     "diameter_km": 3.0},
    "S/2019 S 22":  {"group": "Inuit (Kiviuq)",               "orbital_period_days": 448.48,     "diameter_km": 3.0},
    "Kiviuq":       {"group": "Inuit (Kiviuq)",               "orbital_period_days": 448.91,     "diameter_km": 17.0},
    "S/2023 S 2":   {"group": "Inuit (Kiviuq)",               "orbital_period_days": 449.05,     "diameter_km": 3.0},
    "S/2019 S 23":  {"group": "Inuit (Kiviuq)",               "orbital_period_days": 449.08,     "diameter_km": 3.0},
    "S/2020 S 12":  {"group": "Inuit (Kiviuq)",               "orbital_period_days": 449.33,     "diameter_km": 3.0},
    "S/2005 S 4":   {"group": "Inuit (Kiviuq)",               "orbital_period_days": 449.93,     "diameter_km": 5.0},
    "S/2019 S 25":  {"group": "Inuit (Kiviuq)",               "orbital_period_days": 450.22,     "diameter_km": 4.0},
    "S/2020 S 1":   {"group": "Inuit (Kiviuq)",               "orbital_period_days": 450.77,     "diameter_km": 4.0},
    "Ijiraq":       {"group": "Inuit (Kiviuq)",               "orbital_period_days": 451.12,     "diameter_km": 13.0},
    "S/2019 S 24":  {"group": "Inuit (Kiviuq)",               "orbital_period_days": 452.07,     "diameter_km": 4.0},
    "S/2007 S 10":  {"group": "Inuit (Kiviuq)",               "orbital_period_days": 452.36,     "diameter_km": 4.0},
    "S/2019 S 26":  {"group": "Inuit (Kiviuq)",               "orbital_period_days": 453.89,     "diameter_km": 3.0},
    "S/2020 S 13":  {"group": "Inuit (Kiviuq)",               "orbital_period_days": 455.39,     "diameter_km": 3.0},
    "S/2023 S 6":   {"group": "Inuit (Kiviuq)",               "orbital_period_days": 487.91,     "diameter_km": 3.0},
    "S/2023 S 7":   {"group": "Inuit (Kiviuq)",               "orbital_period_days": 499.01,     "diameter_km": 4.0},
    "Paaliaq":      {"group": "Inuit",                        "orbital_period_days": 685.72,     "diameter_km": 25.0},
    "S/2004 S 31":  {"group": "Inuit (Siarnaq)",              "orbital_period_days": 863.92,     "diameter_km": 5.0},
    "S/2019 S 14":  {"group": "Inuit (Siarnaq)",              "orbital_period_days": 890.59,     "diameter_km": 4.0},
    "S/2023 S 19":  {"group": "Inuit (Siarnaq)",              "orbital_period_days": 870.92,     "diameter_km": 3.0},
    "S/2023 S 3":   {"group": "Inuit (Siarnaq)",              "orbital_period_days": 875.00,     "diameter_km": 3.0},
    "S/2020 S 19":  {"group": "Inuit (Siarnaq)",              "orbital_period_days": 881.04,     "diameter_km": 3.0},
    "Tarqeq":       {"group": "Inuit (Siarnaq)",              "orbital_period_days": 882.85,     "diameter_km": 7.0},
    "Siarnaq":      {"group": "Inuit (Siarnaq)",              "orbital_period_days": 892.68,     "diameter_km": 39.3},
    "S/2019 S 32":  {"group": "Inuit (Siarnaq)",              "orbital_period_days": 898.71,     "diameter_km": 5.0},
    "S/2020 S 3":   {"group": "Inuit (Siarnaq)",              "orbital_period_days": 905.84,     "diameter_km": 3.0},
    "S/2005 S 6":   {"group": "Inuit (Siarnaq)",              "orbital_period_days": 909.58,     "diameter_km": 4.0},
    "S/2019 S 6":   {"group": "Inuit (Siarnaq)",              "orbital_period_days": 917.11,     "diameter_km": 5.0},
    "S/2004 S 58":  {"group": "Inuit (Siarnaq)",              "orbital_period_days": 920.80,     "diameter_km": 5.0},
    "S/2006 S 23":  {"group": "Inuit (Siarnaq)",              "orbital_period_days": 921.86,     "diameter_km": 3.0},
    "S/2020 S 5":   {"group": "Inuit (Siarnaq)",              "orbital_period_days": 931.19,     "diameter_km": 3.0},
    "S/2023 S 22":  {"group": "Inuit (Siarnaq)",              "orbital_period_days": 945.37,     "diameter_km": 4.0},

    # --- Gallic Group ---
    "Albiorix":     {"group": "Gallic",                       "orbital_period_days": 779.07,     "diameter_km": 28.6},
    "S/2020 S 15":  {"group": "Gallic",                       "orbital_period_days": 807.82,     "diameter_km": 3.0},
    "Bebhionn":     {"group": "Gallic",                       "orbital_period_days": 829.64,     "diameter_km": 6.0},
    "S/2007 S 8":   {"group": "Gallic",                       "orbital_period_days": 831.21,     "diameter_km": 4.0},
    "S/2004 S 29":  {"group": "Gallic",                       "orbital_period_days": 832.27,     "diameter_km": 5.0},
    "S/2019 S 29":  {"group": "Gallic",                       "orbital_period_days": 853.62,     "diameter_km": 3.0},
    "S/2023 S 18":  {"group": "Gallic",                       "orbital_period_days": 855.65,     "diameter_km": 3.0},
    "S/2023 S 17":  {"group": "Gallic",                       "orbital_period_days": 855.94,     "diameter_km": 3.0},
    "S/2007 S 11":  {"group": "Gallic",                       "orbital_period_days": 859.53,     "diameter_km": 4.0},
    "Erriapus":     {"group": "Gallic",                       "orbital_period_days": 864.92,     "diameter_km": 10.0},
    "S/2019 S 31":  {"group": "Gallic",                       "orbital_period_days": 882.24,     "diameter_km": 3.0},
    "Tarvos":       {"group": "Gallic",                       "orbital_period_days": 917.98,     "diameter_km": 15.0},
    "S/2020 S 4":   {"group": "Gallic",                       "orbital_period_days": 919.52,     "diameter_km": 3.0},
    "S/2019 S 34":  {"group": "Gallic",                       "orbital_period_days": 935.45,     "diameter_km": 3.0},
    "S/2005 S 7":   {"group": "Gallic",                       "orbital_period_days": 939.75,     "diameter_km": 3.0},
    "S/2006 S 12":  {"group": "Gallic",                       "orbital_period_days": 1022.29,    "diameter_km": 4.0},
    "S/2004 S 24":  {"group": "Gallic",                       "orbital_period_days": 1331.32,    "diameter_km": 4.0},

    # --- Norse Group ---
    "S/2023 S 50":  {"group": "Norse (Mundilfari)",           "orbital_period_days": -469.82,    "diameter_km": 3.0},
    "S/2023 S 38":  {"group": "Norse (low-inclination)",      "orbital_period_days": -546.31,    "diameter_km": 3.0},
    "Phoebe":       {"group": "Norse (Phoebe)",               "orbital_period_days": -550.30,    "diameter_km": 213.0},
    "S/2023 S 9":   {"group": "Norse (Phoebe)",               "orbital_period_days": -564.11,    "diameter_km": 3.0},
    "S/2006 S 20":  {"group": "Norse (Phoebe)",               "orbital_period_days": -565.79,    "diameter_km": 5.0},
    "S/2004 S 56":  {"group": "Norse (Mundilfari)",           "orbital_period_days": -596.69,    "diameter_km": 5.0},
    "S/2023 S 8":   {"group": "Norse (Mundilfari)",           "orbital_period_days": -619.69,    "diameter_km": 3.0},
    "S/2023 S 11":  {"group": "Norse (Mundilfari)",           "orbital_period_days": -621.49,    "diameter_km": 3.0},
    "S/2006 S 9":   {"group": "Norse (Phoebe)",               "orbital_period_days": -645.58,    "diameter_km": 3.0},
    "S/2006 S 21":  {"group": "Norse (Mundilfari)",           "orbital_period_days": -684.28,    "diameter_km": 3.0},
    "S/2006 S 22":  {"group": "Norse (Phoebe)",               "orbital_period_days": -693.41,    "diameter_km": 3.0},
    "S/2023 S 13":  {"group": "Norse (Mundilfari)",           "orbital_period_days": -699.18,    "diameter_km": 3.0},
    "S/2023 S 10":  {"group": "Norse (Mundilfari)",           "orbital_period_days": -720.49,    "diameter_km": 3.0},
    "Skathi":       {"group": "Norse (low-inclination)",      "orbital_period_days": -725.73,    "diameter_km": 8.0},
    "S/2023 S 12":  {"group": "Norse (Mundilfari)",           "orbital_period_days": -741.92,    "diameter_km": 3.0},
    "S/2007 S 5":   {"group": "Norse (Mundilfari)",           "orbital_period_days": -744.01,    "diameter_km": 4.0},
    "S/2007 S 7":   {"group": "Norse (Mundilfari)",           "orbital_period_days": -750.80,    "diameter_km": 4.0},
    "S/2007 S 2":   {"group": "Norse (Phoebe)",               "orbital_period_days": -751.33,    "diameter_km": 5.0},
    "S/2004 S 37":  {"group": "Norse (Mundilfari)",           "orbital_period_days": -752.55,    "diameter_km": 4.0},
    "S/2004 S 47":  {"group": "Norse (Mundilfari)",           "orbital_period_days": -759.22,    "diameter_km": 4.0},
    "S/2004 S 40":  {"group": "Norse (Mundilfari)",           "orbital_period_days": -761.00,    "diameter_km": 4.0},
    "S/2020 S 14":  {"group": "Norse (Mundilfari)",           "orbital_period_days": -768.86,    "diameter_km": 3.0},
    "S/2019 S 27":  {"group": "Norse (Mundilfari)",           "orbital_period_days": -774.63,    "diameter_km": 3.0},
    "S/2019 S 2":   {"group": "Norse (Phoebe)",               "orbital_period_days": -795.67,    "diameter_km": 3.0},
    "S/2020 S 7":   {"group": "Norse (Mundilfari)",           "orbital_period_days": -856.53,    "diameter_km": 3.0},
    "S/2023 S 14":  {"group": "Norse (Mundilfari)",           "orbital_period_days": -816.86,    "diameter_km": 3.0},
    "S/2020 S 16":  {"group": "Norse (Mundilfari)",           "orbital_period_days": -824.92,    "diameter_km": 3.0},
    "S/2023 S 16":  {"group": "Norse (Mundilfari)",           "orbital_period_days": -827.81,    "diameter_km": 3.0},
    "Skoll":        {"group": "Norse (Mundilfari)",           "orbital_period_days": -873.57,    "diameter_km": 5.0},
    "S/2019 S 30":  {"group": "Norse (Mundilfari)",           "orbital_period_days": -879.97,    "diameter_km": 3.0},
    "S/2019 S 28":  {"group": "Norse (Mundilfari)",           "orbital_period_days": -864.09,    "diameter_km": 4.0},
    "S/2019 S 4":   {"group": "Norse (Mundilfari)",           "orbital_period_days": -898.09,    "diameter_km": 3.0},
    "S/2020 S 20":  {"group": "Norse (Mundilfari)",           "orbital_period_days": -901.53,    "diameter_km": 3.0},
    "S/2004 S 41":  {"group": "Norse (Mundilfari)",           "orbital_period_days": -908.89,    "diameter_km": 4.0},
    "S/2004 S 57":  {"group": "Norse (Mundilfari)",           "orbital_period_days": -913.07,    "diameter_km": 4.0},
    "S/2006 S 24":  {"group": "Norse (Mundilfari)",           "orbital_period_days": -917.56,    "diameter_km": 3.0},
    "S/2023 S 30":  {"group": "Norse (low-inclination)",      "orbital_period_days": -919.71,    "diameter_km": 3.0},
    "S/2004 S 42":  {"group": "Norse (Mundilfari)",           "orbital_period_days": -919.88,    "diameter_km": 4.0},
    "S/2023 S 15":  {"group": "Norse (Mundilfari)",           "orbital_period_days": -919.93,    "diameter_km": 3.0},
    "Hyrrokkin":    {"group": "Norse (low-inclination)",      "orbital_period_days": -927.46,    "diameter_km": 8.0},
    "S/2023 S 24":  {"group": "Norse (Mundilfari)",           "orbital_period_days": -928.25,    "diameter_km": 3.0},
    "Greip":        {"group": "Norse (Phoebe)",               "orbital_period_days": -930.44,    "diameter_km": 5.0},
    "S/2004 S 13":  {"group": "Norse (Mundilfari)",           "orbital_period_days": -936.09,    "diameter_km": 4.0},
    "S/2007 S 6":   {"group": "Norse (Mundilfari)",           "orbital_period_days": -942.98,    "diameter_km": 3.0},
    "S/2019 S 35":  {"group": "Norse (Mundilfari)",           "orbital_period_days": -944.00,    "diameter_km": 3.0},
    "S/2006 S 25":  {"group": "Norse (Mundilfari)",           "orbital_period_days": -945.07,    "diameter_km": 3.0},
    "Mundilfari":   {"group": "Norse (Mundilfari)",           "orbital_period_days": -946.29,    "diameter_km": 7.0},
    "S/2006 S 26":  {"group": "Norse (Mundilfari)",           "orbital_period_days": -948.67,    "diameter_km": 3.0},
    "S/2019 S 33":  {"group": "Norse (Mundilfari)",           "orbital_period_days": -954.53,    "diameter_km": 4.0},
    "S/2006 S 1":   {"group": "Norse (Kari)",                 "orbital_period_days": -958.32,    "diameter_km": 5.0},
    "S/2023 S 23":  {"group": "Norse (Mundilfari)",           "orbital_period_days": -961.22,    "diameter_km": 3.0},
    "S/2020 S 21":  {"group": "Norse (Mundilfari)",           "orbital_period_days": -967.26,    "diameter_km": 3.0},
    "S/2004 S 43":  {"group": "Norse (Mundilfari)",           "orbital_period_days": -972.85,    "diameter_km": 4.0},
    "S/2006 S 10":  {"group": "Norse (Mundilfari)",           "orbital_period_days": -976.34,    "diameter_km": 3.0},
    "S/2019 S 5":   {"group": "Norse (Mundilfari)",           "orbital_period_days": -984.87,    "diameter_km": 3.0},
    "S/2023 S 25":  {"group": "Norse (Mundilfari)",           "orbital_period_days": -988.53,    "diameter_km": 3.0},
    "S/2004 S 59":  {"group": "Norse (Mundilfari)",           "orbital_period_days": -991.18,    "diameter_km": 3.0},
    "S/2006 S 27":  {"group": "Norse (Mundilfari)",           "orbital_period_days": -993.79,    "diameter_km": 4.0},
    "Gridr":        {"group": "Norse (Mundilfari)",           "orbital_period_days": -997.33,    "diameter_km": 4.0},
    "Bergelmir":    {"group": "Norse (Mundilfari)",           "orbital_period_days": -998.62,    "diameter_km": 5.0},
    "Jarnsaxa":     {"group": "Norse (Mundilfari)",           "orbital_period_days": -999.13,    "diameter_km": 6.0},
    "Narvi":        {"group": "Norse (low-inclination)",      "orbital_period_days": -999.94,    "diameter_km": 7.0},
    "S/2023 S 44":  {"group": "Norse (Mundilfari)",           "orbital_period_days": -1000.47,   "diameter_km": 3.0},
    "Suttungr":     {"group": "Norse (Phoebe)",               "orbital_period_days": -1008.25,   "diameter_km": 7.0},
    "S/2020 S 22":  {"group": "Norse (Mundilfari)",           "orbital_period_days": -1012.24,   "diameter_km": 3.0},
    "S/2004 S 44":  {"group": "Norse (Mundilfari)",           "orbital_period_days": -1017.91,   "diameter_km": 5.0},
    "S/2004 S 60":  {"group": "Norse (Phoebe)",               "orbital_period_days": -1018.13,   "diameter_km": 3.0},
    "S/2007 S 3":   {"group": "Norse (Phoebe)",               "orbital_period_days": -1025.70,   "diameter_km": 5.0},
    "S/2004 S 45":  {"group": "Norse (Kari)",                 "orbital_period_days": -1031.86,   "diameter_km": 4.0},
    "Hati":         {"group": "Norse (Mundilfari)",           "orbital_period_days": -1032.02,   "diameter_km": 5.0},
    "S/2004 S 17":  {"group": "Norse (Mundilfari)",           "orbital_period_days": -1032.37,   "diameter_km": 4.0},
    "S/2006 S 11":  {"group": "Norse (Phoebe)",               "orbital_period_days": -1033.35,   "diameter_km": 3.0},
    "S/2004 S 12":  {"group": "Norse (Mundilfari)",           "orbital_period_days": -1040.39,   "diameter_km": 4.0},
    "S/2020 S 23":  {"group": "Norse (Mundilfari)",           "orbital_period_days": -1040.38,   "diameter_km": 3.0},
    "S/2023 S 27":  {"group": "Norse (low-inclination)",      "orbital_period_days": -1041.85,   "diameter_km": 3.0},
    "Eggther":      {"group": "Norse (Mundilfari)",           "orbital_period_days": -1043.80,   "diameter_km": 6.0},
    "S/2023 S 28":  {"group": "Norse (Mundilfari)",           "orbital_period_days": -1046.56,   "diameter_km": 3.0},
    "S/2023 S 37":  {"group": "Norse (Phoebe)",               "orbital_period_days": -1047.39,   "diameter_km": 3.0},
    "S/2023 S 26":  {"group": "Norse (Mundilfari)",           "orbital_period_days": -1047.76,   "diameter_km": 3.0},
    "S/2019 S 36":  {"group": "Norse (Mundilfari)",           "orbital_period_days": -1048.42,   "diameter_km": 3.0},
    "S/2006 S 13":  {"group": "Norse (Mundilfari)",           "orbital_period_days": -1052.32,   "diameter_km": 4.0},
    "S/2019 S 37":  {"group": "Norse (low-inclination)",      "orbital_period_days": -1055.78,   "diameter_km": 3.0},
    "S/2023 S 48":  {"group": "Norse (Mundilfari)",           "orbital_period_days": -1058.35,   "diameter_km": 3.0},
    "S/2023 S 29":  {"group": "Norse (Phoebe)",               "orbital_period_days": -1059.42,   "diameter_km": 3.0},
    "S/2007 S 9":   {"group": "Norse (Mundilfari)",           "orbital_period_days": -1069.81,   "diameter_km": 4.0},
    "S/2019 S 7":   {"group": "Norse (Phoebe)",               "orbital_period_days": -1070.80,   "diameter_km": 4.0},
    "S/2019 S 8":   {"group": "Norse (Phoebe)",               "orbital_period_days": -1078.86,   "diameter_km": 4.0},
    "Farbauti":     {"group": "Norse (Kari)",                 "orbital_period_days": -1079.12,   "diameter_km": 5.0},
    "Thrymr":       {"group": "Norse (Phoebe)",               "orbital_period_days": -1082.23,   "diameter_km": 8.0},
    "Bestla":       {"group": "Norse (low-inclination)",      "orbital_period_days": -1082.94,   "diameter_km": 7.0},
    "S/2019 S 9":   {"group": "Norse (Mundilfari)",           "orbital_period_days": -1084.62,   "diameter_km": 4.0},
    "S/2023 S 32":  {"group": "Norse (Mundilfari)",           "orbital_period_days": -1092.24,   "diameter_km": 2.0},
    "S/2004 S 46":  {"group": "Norse (Phoebe)",               "orbital_period_days": -1096.99,   "diameter_km": 3.0},
    "Angrboda":     {"group": "Norse (Phoebe)",               "orbital_period_days": -1103.20,   "diameter_km": 4.0},
    "S/2020 S 24":  {"group": "Norse (Mundilfari)",           "orbital_period_days": -1105.41,   "diameter_km": 3.0},
    "S/2019 S 11":  {"group": "Norse (low-inclination)",      "orbital_period_days": -1109.11,   "diameter_km": 4.0},
    "Aegir":        {"group": "Norse (Mundilfari)",           "orbital_period_days": -1109.13,   "diameter_km": 6.0},
    "S/2019 S 10":  {"group": "Norse (Mundilfari)",           "orbital_period_days": -1111.99,   "diameter_km": 3.0},
    "Beli":         {"group": "Norse (Mundilfari)",           "orbital_period_days": -1112.27,   "diameter_km": 4.0},
    "S/2023 S 31":  {"group": "Norse (Mundilfari)",           "orbital_period_days": -1114.29,   "diameter_km": 3.0},
    "S/2020 S 25":  {"group": "Norse (Mundilfari)",           "orbital_period_days": -1117.09,   "diameter_km": 3.0},
    "S/2023 S 34":  {"group": "Norse (Mundilfari)",           "orbital_period_days": -1120.38,   "diameter_km": 3.0},
    "S/2023 S 39":  {"group": "Norse (Mundilfari)",           "orbital_period_days": -1121.99,   "diameter_km": 3.0},
    "S/2019 S 12":  {"group": "Norse (Mundilfari)",           "orbital_period_days": -1127.60,   "diameter_km": 4.0},
    "Gerd":         {"group": "Norse (Phoebe)",               "orbital_period_days": -1131.91,   "diameter_km": 4.0},
    "S/2019 S 13":  {"group": "Norse (Phoebe)",               "orbital_period_days": -1133.27,   "diameter_km": 3.0},
    "S/2004 S 61":  {"group": "Norse (Mundilfari)",           "orbital_period_days": -1135.06,   "diameter_km": 4.0},
    "S/2006 S 14":  {"group": "Norse (Mundilfari)",           "orbital_period_days": -1141.27,   "diameter_km": 3.0},
    "S/2023 S 40":  {"group": "Norse (Mundilfari)",           "orbital_period_days": -1141.48,   "diameter_km": 3.0},
    "Gunnlod":      {"group": "Norse (Mundilfari)",           "orbital_period_days": -1147.74,   "diameter_km": 4.0},
    "S/2019 S 15":  {"group": "Norse (Mundilfari)",           "orbital_period_days": -1151.66,   "diameter_km": 3.0},
    "S/2020 S 6":   {"group": "Norse (Mundilfari)",           "orbital_period_days": -1156.81,   "diameter_km": 3.0},
    "S/2020 S 26":  {"group": "Norse (Mundilfari)",           "orbital_period_days": -1157.77,   "diameter_km": 3.0},
    "S/2023 S 41":  {"group": "Norse (Phoebe)",               "orbital_period_days": -1159.52,   "diameter_km": 3.0},
    "S/2004 S 7":   {"group": "Norse (Mundilfari)",           "orbital_period_days": -1162.93,   "diameter_km": 5.0},
    "S/2006 S 3":   {"group": "Norse (Kari)",                 "orbital_period_days": -1165.02,   "diameter_km": 5.0},
    "S/2005 S 5":   {"group": "Norse (Mundilfari)",           "orbital_period_days": -1165.96,   "diameter_km": 3.0},
    "Skrymir":      {"group": "Norse (Phoebe)",               "orbital_period_days": -1172.72,   "diameter_km": 4.0},
    "S/2023 S 33":  {"group": "Norse (Kari)",                 "orbital_period_days": -1187.07,   "diameter_km": 3.0},
    "S/2006 S 16":  {"group": "Norse (Mundilfari)",           "orbital_period_days": -1195.13,   "diameter_km": 3.0},
    "S/2023 S 49":  {"group": "Norse (Mundilfari)",           "orbital_period_days": -1198.99,   "diameter_km": 3.0},
    "S/2020 S 30":  {"group": "Norse (Kari)",                 "orbital_period_days": -1201.02,   "diameter_km": 3.0},
    "S/2006 S 15":  {"group": "Norse (Mundilfari)",           "orbital_period_days": -1201.69,   "diameter_km": 4.0},
    "S/2020 S 27":  {"group": "Norse (low-inclination)",      "orbital_period_days": -1202.02,   "diameter_km": 3.0},
    "S/2023 S 42":  {"group": "Norse (Mundilfari)",           "orbital_period_days": -1204.81,   "diameter_km": 3.0},
    "S/2004 S 28":  {"group": "Norse (Mundilfari)",           "orbital_period_days": -1207.18,   "diameter_km": 5.0},
    "S/2020 S 32":  {"group": "Norse (Mundilfari)",           "orbital_period_days": -1208.85,   "diameter_km": 3.0},
    "S/2006 S 28":  {"group": "Norse (Phoebe)",               "orbital_period_days": -1214.53,   "diameter_km": 4.0},
    "S/2020 S 8":   {"group": "Norse (Mundilfari)",           "orbital_period_days": -1215.61,   "diameter_km": 3.0},
    "S/2020 S 28":  {"group": "Norse (Mundilfari)",           "orbital_period_days": -1217.81,   "diameter_km": 3.0},
    "Alvaldi":      {"group": "Norse (Phoebe)",               "orbital_period_days": -1217.80,   "diameter_km": 6.0},
    "S/2019 S 38":  {"group": "Norse (Mundilfari)",           "orbital_period_days": -1218.27,   "diameter_km": 3.0},
    "Kari":         {"group": "Norse (Kari)",                 "orbital_period_days": -1220.98,   "diameter_km": 6.0},
    "S/2004 S 48":  {"group": "Norse (Mundilfari)",           "orbital_period_days": -1229.86,   "diameter_km": 4.0},
    "S/2023 S 36":  {"group": "Norse (Mundilfari)",           "orbital_period_days": -1237.61,   "diameter_km": 3.0},
    "Geirrod":      {"group": "Norse (Kari)",                 "orbital_period_days": -1240.05,   "diameter_km": 4.0},
    "S/2023 S 35":  {"group": "Norse (Mundilfari)",           "orbital_period_days": -1240.76,   "diameter_km": 3.0},
    "S/2020 S 29":  {"group": "Norse (Mundilfari)",           "orbital_period_days": -1243.45,   "diameter_km": 3.0},
    "Fenrir":       {"group": "Norse (Mundilfari)",           "orbital_period_days": -1245.92,   "diameter_km": 4.0},
    "S/2004 S 50":  {"group": "Norse (Mundilfari)",           "orbital_period_days": -1247.19,   "diameter_km": 3.0},
    "S/2006 S 17":  {"group": "Norse (Mundilfari)",           "orbital_period_days": -1250.46,   "diameter_km": 4.0},
    "S/2004 S 49":  {"group": "Norse (Mundilfari)",           "orbital_period_days": -1251.68,   "diameter_km": 4.0},
    "S/2020 S 34":  {"group": "Norse (Mundilfari)",           "orbital_period_days": -1254.61,   "diameter_km": 3.0},
    "S/2020 S 31":  {"group": "Norse (Mundilfari)",           "orbital_period_days": -1256.50,   "diameter_km": 3.0},
    "S/2023 S 43":  {"group": "Norse (Mundilfari)",           "orbital_period_days": -1265.57,   "diameter_km": 3.0},
    "S/2019 S 17":  {"group": "Norse (Kari)",                 "orbital_period_days": -1278.96,   "diameter_km": 4.0},
    "Surtur":       {"group": "Norse (Mundilfari)",           "orbital_period_days": -1281.14,   "diameter_km": 6.0},
    "S/2006 S 18":  {"group": "Norse (Mundilfari)",           "orbital_period_days": -1282.09,   "diameter_km": 4.0},
    "S/2020 S 36":  {"group": "Norse (Mundilfari)",           "orbital_period_days": -1286.03,   "diameter_km": 3.0},
    "Loge":         {"group": "Norse (Mundilfari)",           "orbital_period_days": -1295.52,   "diameter_km": 5.0},
    "S/2020 S 33":  {"group": "Norse (Mundilfari)",           "orbital_period_days": -1295.85,   "diameter_km": 3.0},
    "Ymir":         {"group": "Norse (Phoebe)",               "orbital_period_days": -1298.68,   "diameter_km": 19.0},
    "S/2020 S 35":  {"group": "Norse (Phoebe)",               "orbital_period_days": -1304.97,   "diameter_km": 3.0},
    "S/2019 S 19":  {"group": "Norse (Kari)",                 "orbital_period_days": -1306.16,   "diameter_km": 3.0},
    "S/2019 S 18":  {"group": "Norse (Kari)",                 "orbital_period_days": -1314.27,   "diameter_km": 3.0},
    "S/2004 S 21":  {"group": "Norse (Kari)",                 "orbital_period_days": -1316.12,   "diameter_km": 4.0},
    "S/2004 S 39":  {"group": "Norse (Mundilfari)",           "orbital_period_days": -1318.74,   "diameter_km": 4.0},
    "S/2019 S 16":  {"group": "Norse (Mundilfari)",           "orbital_period_days": -1324.95,   "diameter_km": 3.0},
    "S/2004 S 53":  {"group": "Norse (Mundilfari)",           "orbital_period_days": -1326.18,   "diameter_km": 4.0},
    "S/2004 S 36":  {"group": "Norse (Kari)",                 "orbital_period_days": -1335.80,   "diameter_km": 4.0},
    "S/2023 S 45":  {"group": "Norse (Mundilfari)",           "orbital_period_days": -1339.85,   "diameter_km": 3.0},
    "Thiazzi":      {"group": "Norse (Mundilfari)",           "orbital_period_days": -1351.83,   "diameter_km": 4.0},
    "S/2020 S 38":  {"group": "Norse (Mundilfari)",           "orbital_period_days": -1352.43,   "diameter_km": 4.0},
    "S/2019 S 20":  {"group": "Norse (Kari)",                 "orbital_period_days": -1360.47,   "diameter_km": 3.0},
    "S/2020 S 37":  {"group": "Norse (Phoebe)",               "orbital_period_days": -1366.82,   "diameter_km": 3.0},
    "S/2019 S 39":  {"group": "Norse (Phoebe)",               "orbital_period_days": -1369.64,   "diameter_km": 3.0},
    "S/2020 S 40":  {"group": "Norse (Mundilfari)",           "orbital_period_days": -1369.76,   "diameter_km": 3.0},
    "S/2006 S 19":  {"group": "Norse (Phoebe)",               "orbital_period_days": -1371.02,   "diameter_km": 4.0},
    "S/2019 S 40":  {"group": "Norse (Mundilfari)",           "orbital_period_days": -1395.88,   "diameter_km": 3.0},
    "S/2019 S 42":  {"group": "Norse (Mundilfari)",           "orbital_period_days": -1397.98,   "diameter_km": 4.0},
    "S/2004 S 34":  {"group": "Norse (Mundilfari)",           "orbital_period_days": -1400.93,   "diameter_km": 4.0},
    "S/2020 S 39":  {"group": "Norse (Mundilfari)",           "orbital_period_days": -1411.15,   "diameter_km": 3.0},
    "S/2019 S 41":  {"group": "Norse (Mundilfari)",           "orbital_period_days": -1431.30,   "diameter_km": 3.0},
    "S/2023 S 46":  {"group": "Norse (low-inclination)",      "orbital_period_days": -1450.27,   "diameter_km": 3.0},
    "Fornjot":      {"group": "Norse (Mundilfari)",           "orbital_period_days": -1470.36,   "diameter_km": 6.0},
    "S/2023 S 47":  {"group": "Norse (Mundilfari)",           "orbital_period_days": -1485.04,   "diameter_km": 3.0},
    "S/2004 S 51":  {"group": "Norse (Mundilfari)",           "orbital_period_days": -1494.41,   "diameter_km": 4.0},
    "S/2006 S 29":  {"group": "Norse (Kari)",                 "orbital_period_days": -1494.78,   "diameter_km": 3.0},
    "S/2020 S 10":  {"group": "Norse (Mundilfari)",           "orbital_period_days": -1503.97,   "diameter_km": 3.0},
    "S/2020 S 42":  {"group": "Norse (Mundilfari)",           "orbital_period_days": -1505.31,   "diameter_km": 3.0},
    "S/2020 S 9":   {"group": "Norse (Mundilfari)",           "orbital_period_days": -1512.38,   "diameter_km": 4.0},
    "S/2023 S 5":   {"group": "Norse (Mundilfari)",           "orbital_period_days": -1528.04,   "diameter_km": 3.0},
    "S/2020 S 41":  {"group": "Norse (Mundilfari)",           "orbital_period_days": -1554.40,   "diameter_km": 3.0},
    "S/2004 S 26":  {"group": "Norse (Phoebe)",               "orbital_period_days": -1574.25,   "diameter_km": 5.0},
    "S/2019 S 21":  {"group": "Norse (Mundilfari)",           "orbital_period_days": -1605.28,   "diameter_km": 4.0},
    "S/2004 S 52":  {"group": "Norse (Mundilfari)",           "orbital_period_days": -1605.89,   "diameter_km": 3.0},
    "S/2020 S 43":  {"group": "Norse (Mundilfari)",           "orbital_period_days": -1625.29,   "diameter_km": 3.0},
    "S/2019 S 43":  {"group": "Norse (Mundilfari)",           "orbital_period_days": -1625.90,   "diameter_km": 3.0},
    "S/2019 S 44":  {"group": "Norse (Phoebe)",               "orbital_period_days": -1638.11,   "diameter_km": 3.0},
    "S/2020 S 44":  {"group": "Norse (Mundilfari)",           "orbital_period_days": -1680.64,   "diameter_km": 3.0},
    "S/2020 S 17":  {"group": "Norse (low-inclination)",      "orbital_period_days": -834.45,    "diameter_km": 4.0},
    "S/2020 S 18":  {"group": "Norse (Mundilfari)",           "orbital_period_days": -885.12,    "diameter_km": 3.0},
    "S/2023 S 4":   {"group": "Norse (Mundilfari)",           "orbital_period_days": -884.11,    "diameter_km": 3.0},
    "S/2023 S 20":  {"group": "Norse (low-inclination)",      "orbital_period_days": -846.77,    "diameter_km": 3.0},
    "S/2023 S 21":  {"group": "Norse (Mundilfari)",           "orbital_period_days": -883.31,    "diameter_km": 3.0},
    "S/2019 S 3":   {"group": "Norse (Mundilfari)",           "orbital_period_days": -833.19,    "diameter_km": 4.0},
    "S/2020 S 2":   {"group": "Norse (Mundilfari)",           "orbital_period_days": -891.86,    "diameter_km": 3.0},
}

# Note: Negative orbital periods indicate retrograde orbits.
# Diameter values are approximate for most irregular/provisional moons.

if __name__ == "__main__":
    # Example lookup
    name = "Titan"
    moon = saturn_moons[name]
    print(f"{name}: group={moon['group']}, period={moon['orbital_period_days']} days, diameter={moon['diameter_km']} km\n")

    # Summary stats
    named   = [k for k in saturn_moons if not k.startswith("S/")]
    unnamed = [k for k in saturn_moons if k.startswith("S/")]
    print(f"Total moons in table: {len(saturn_moons)}")
    print(f"  Named:       {len(named)}")
    print(f"  Provisional: {len(unnamed)}")

    # Print all moons sorted by orbital period
    print(f"\n{'Moon':<20} {'Group':<35} {'Period (days)':>14} {'Diameter (km)':>14}")
    print("-" * 88)
    for name, data in sorted(saturn_moons.items(), key=lambda x: x[1]["orbital_period_days"]):
        print(f"{name:<20} {data['group']:<35} {data['orbital_period_days']:>14.2f} {data['diameter_km']:>14.2f}")